# Generated by Django 3.0.5 on 2021-12-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211207_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_6',
        ),
    ]
