# Generated by Django 3.0.5 on 2022-04-26 21:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220426_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
